---
title: "HW3"
author: "Mark Heinen"
format: html
editor: visual
---

## Setup

Loading in file hw2 list file

```{r}
load("hw2_list.rda")
```

## Task 1: Control Flow Practice

Characterizing the post-treatment blood presure measurement as optimal (\<= 120), borderline (120 \< bp \< 130), and high (\> 130). First step is to create a new column in each data frame from above called status

```{r}
bp_list$treatment$status <- character(20) 
bp_list$placebo$status <- character(10)
bp_list
```

Creating a loop to combine a for and if statement in order to fill out the values for status in treatment and placebp 


```{r}

  

for (i in 1:nrow(bp_list$treatment)){
  bp <- bp_list$treatment$post_bp
  if(bp[i] <= 120){
   bp_list$treatment$status[i] <- "optimal"
  }else if (bp[i] > 120 & bp[i] <= 130 ){
    bp_list$treatment$status[i] <- "borderline"
  }else if (bp[i] > 130 ){ 
    bp_list$treatment$status[i] <- "high"
  }
}

```

```{r}
for (i in 1:nrow(bp_list$placebo)){
  bp <- bp_list$placebo$post_bp
  if(bp[i] <= 120){
   bp_list$placebo$status[i] <- "optimal"
  }else if (bp[i] > 120 & bp[i] <= 130 ){
    bp_list$placebo$status[i] <- "borderline"
  }else if (bp[i] > 130 ){ 
    bp_list$placebo$status[i] <- "high"
  }
}
```

```{r}
bp_list
```

```
